2019-06-30 18:45:45,379 [INFO] Creating database transactions at ./database/transactions.db
2019-06-30 18:45:45,380 [INFO] 127.0.0.1 - - [30/Jun/2019 18:45:45] "GET /expenses HTTP/1.1" 200 -
2019-06-30 19:03:07,700 [INFO] Creating database transactions at ./database/transactions.db
2019-06-30 19:03:07,702 [INFO] 127.0.0.1 - - [30/Jun/2019 19:03:07] "GET /expenses HTTP/1.1" 200 -
2019-06-30 19:03:07,882 [INFO] 127.0.0.1 - - [30/Jun/2019 19:03:07] "GET /favicon.ico HTTP/1.1" 404 -
2019-06-30 19:08:54,236 [INFO] Creating database transactions at ./database/transactions.db
2019-06-30 19:08:54,237 [INFO] 127.0.0.1 - - [30/Jun/2019 19:08:54] "GET /expenses HTTP/1.1" 200 -
2019-06-30 19:08:55,843 [INFO] 127.0.0.1 - - [30/Jun/2019 19:08:55] "GET / HTTP/1.1" 200 -
2019-06-30 19:08:56,006 [INFO] 127.0.0.1 - - [30/Jun/2019 19:08:56] "GET / HTTP/1.1" 200 -
2019-06-30 19:09:37,415 [INFO] 127.0.0.1 - - [30/Jun/2019 19:09:37] "GET / HTTP/1.1" 200 -
2019-06-30 19:09:37,862 [INFO] 127.0.0.1 - - [30/Jun/2019 19:09:37] "GET /favicon.ico HTTP/1.1" 404 -
2019-06-30 21:41:21,632 [INFO] Creating database transactions at ./database/transactions.db
2019-06-30 21:41:21,633 [ERRO] Exception on /expenses [GET]
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/anaconda3/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/anaconda3/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/anaconda3/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "app.py", line 29, in get
    results = fm.getExpenses()
  File "/Users/narenuday/Desktop/Finance Manager/finance_manager/fm/financemanager.py", line 53, in getExpenses
    queries.TRANSACTIONS_ALL())
TypeError: 'str' object is not callable
2019-06-30 21:41:21,638 [INFO] 127.0.0.1 - - [30/Jun/2019 21:41:21] "GET /expenses HTTP/1.1" 500 -
2019-06-30 21:41:47,259 [INFO] Creating database transactions at ./database/transactions.db
2019-06-30 21:41:47,260 [INFO] 127.0.0.1 - - [30/Jun/2019 21:41:47] "GET /expenses/category HTTP/1.1" 200 -
2019-06-30 21:41:59,542 [INFO] Creating database transactions at ./database/transactions.db
2019-06-30 21:41:59,543 [INFO] 127.0.0.1 - - [30/Jun/2019 21:41:59] "GET /expenses/category/1 HTTP/1.1" 200 -
2019-06-30 21:42:00,773 [INFO] Creating database transactions at ./database/transactions.db
2019-06-30 21:42:00,774 [INFO] 127.0.0.1 - - [30/Jun/2019 21:42:00] "GET /expenses/category/1 HTTP/1.1" 200 -
2019-06-30 21:42:11,603 [INFO] Creating database transactions at ./database/transactions.db
2019-06-30 21:42:11,604 [ERRO] Exception on /expenses [GET]
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/anaconda3/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/anaconda3/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/anaconda3/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "app.py", line 29, in get
    results = fm.getExpenses()
  File "/Users/narenuday/Desktop/Finance Manager/finance_manager/fm/financemanager.py", line 53, in getExpenses
    queries.TRANSACTIONS_ALL())
TypeError: 'str' object is not callable
2019-06-30 21:42:11,604 [INFO] 127.0.0.1 - - [30/Jun/2019 21:42:11] "GET /expenses HTTP/1.1" 500 -
2019-06-30 21:43:18,995 [INFO] Creating database transactions at ./database/transactions.db
2019-06-30 21:43:18,995 [ERRO] Exception on /expenses [GET]
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/anaconda3/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/anaconda3/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/anaconda3/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "app.py", line 29, in get
    results = fm.getExpenses()
  File "/Users/narenuday/Desktop/Finance Manager/finance_manager/fm/financemanager.py", line 53, in getExpenses
    queries.TRANSACTIONS_ALL)
TypeError: 'str' object is not callable
2019-06-30 21:43:18,997 [INFO] 127.0.0.1 - - [30/Jun/2019 21:43:18] "GET /expenses HTTP/1.1" 500 -
2019-06-30 21:43:58,064 [INFO] Creating database transactions at ./database/transactions.db
2019-06-30 21:43:58,070 [INFO] 127.0.0.1 - - [30/Jun/2019 21:43:58] "GET /expenses HTTP/1.1" 200 -
2019-06-30 23:17:33,132 [INFO] Creating database transactions at ./database/transactions.db
2019-06-30 23:17:33,136 [INFO] 127.0.0.1 - - [30/Jun/2019 23:17:33] "GET /expenses HTTP/1.1" 200 -
2019-06-30 23:18:05,187 [INFO] Creating database transactions at ./database/transactions.db
2019-06-30 23:18:05,190 [INFO] 127.0.0.1 - - [30/Jun/2019 23:18:05] "GET /expenses HTTP/1.1" 200 -
2019-06-30 23:19:13,579 [INFO] Creating database transactions at ./database/transactions.db
2019-06-30 23:19:13,582 [INFO] 127.0.0.1 - - [30/Jun/2019 23:19:13] "GET /expenses HTTP/1.1" 200 -
2019-06-30 23:19:31,151 [INFO] Creating database transactions at ./database/transactions.db
2019-06-30 23:19:31,155 [INFO] 127.0.0.1 - - [30/Jun/2019 23:19:31] "GET /expenses HTTP/1.1" 200 -
2019-06-30 23:21:06,417 [INFO] Creating database transactions at ./database/transactions.db
2019-06-30 23:21:06,419 [INFO] 127.0.0.1 - - [30/Jun/2019 23:21:06] "GET /expenses/category HTTP/1.1" 200 -
2019-06-30 23:23:23,894 [INFO] Creating database transactions at ./database/transactions.db
2019-06-30 23:23:23,895 [INFO] 127.0.0.1 - - [30/Jun/2019 23:23:23] "GET /expenses/category HTTP/1.1" 200 -
2019-06-30 23:23:57,213 [INFO] Creating database transactions at ./database/transactions.db
2019-06-30 23:23:57,214 [ERRO] Exception on /expenses/category [GET]
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/anaconda3/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/anaconda3/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/anaconda3/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "app.py", line 22, in get
    results = fm.getExpensesGroupbyCategory()
  File "/Users/narenuday/Desktop/Finance Manager/finance_manager/fm/financemanager.py", line 41, in getExpensesGroupbyCategory
    queries.EXPENSES_GROUPBY_CATEGORY_TOTAL)
  File "/Users/narenuday/Desktop/Finance Manager/finance_manager/fm/db.py", line 38, in execute
    self.cursor.execute(query)
sqlite3.OperationalError: near "Amount": syntax error
2019-06-30 23:23:57,218 [INFO] 127.0.0.1 - - [30/Jun/2019 23:23:57] "GET /expenses/category HTTP/1.1" 500 -
2019-06-30 23:24:47,533 [INFO] Creating database transactions at ./database/transactions.db
2019-06-30 23:24:47,535 [INFO] 127.0.0.1 - - [30/Jun/2019 23:24:47] "GET /expenses/category HTTP/1.1" 200 -
2019-06-30 23:32:41,372 [INFO] Creating database transactions at ./database/transactions.db
2019-06-30 23:32:41,376 [INFO] 127.0.0.1 - - [30/Jun/2019 23:32:41] "GET /expenses HTTP/1.1" 200 -
